store/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.blog, name='blog'),
]

store/product/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('show/', views.show),
    path('add_product/', views.product, name="add_product"),
    path('delete/<int:id>', views.destroy),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('raw_sql/', views.raw_sql),
]    

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import api
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('layout/', include('mainApp.urls')),
    path('about/', include('about.urls')),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('checkout/', include('checkout.urls')),
    path('product_detail/', include('product_detail.urls')),
    path('order_complete/', include('order_complete.urls')),
    path('add_to_wishlist/', include('add_to_wishlist.urls')),
    path('login/', include('login.urls')),
    path('product/', include('product.urls')),
    path('profile/', include('user_profile.urls')),
    path('api/v1/', include(api.router.urls))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/product/models.py
from django.db import models

class Color(models.Model):
    color = models.CharField(max_length=20)

class Size(models.Model):
    size = models.CharField(max_length=10) 

# class Image(models.Model):
#     image = models.ImageField(upload_to='product_images/') 

# Create your models here.
class Product(models.Model):  
    pid = models.CharField(max_length=20)  
    pname = models.CharField(max_length=100)  
    pprice = models.IntegerField()
    prating = models.IntegerField(default=0)
    pshort_description = models.CharField(max_length=300, default="") 
    plong_description = models.CharField(max_length=2000, default="")
    pmanufacturer = models.CharField(max_length=2000, default="")

    pimage = models.ImageField(null=True, blank=True,upload_to='product_images/')
    pcolor = models.ManyToManyField(Color)
    psize = models.ManyToManyField(Size)
    class Meta:  
        db_table = "products"

store/product/forms.py
from django import forms  
from product.models import Product, Color, Size

class ProductForm(forms.ModelForm):  
    # pimage = forms.ImageField()
    pcolor = forms.ModelMultipleChoiceField(
        queryset=Color.objects.values_list('color', flat=True),
        widget=forms.CheckboxSelectMultiple
    )
    psize = forms.ModelMultipleChoiceField(
        queryset=Size.objects.values_list('size', flat=True),
        widget=forms.CheckboxSelectMultiple
    )


    class Meta:  
        model = Product 
        fields = "__all__"
        labels = {
            'pcolor': 'Colors'
        }

store/product/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from product.models import Product, Color, Size
from django.http import JsonResponse
from product.forms import ProductForm
import json
from rest_framework.parsers import FileUploadParser
from rest_framework import response
from rest_framework.decorators import action
from rest_framework import parsers

from rest_framework import viewsets
from . import serializers
from rest_framework.response import Response

# Create your views here.
def show(request):
    products = Product.objects.all()  
    return render(request,"show.html",{'products':products}) 

def product(request):  
    if request.method == "POST":   
        print("inside post")
        print(request.POST)
        sizes = request.POST.getlist("psize")
        all_sizes = []
        for size in sizes:
            print("checking for size", size)
            s = Size.objects.filter(size=size)
            for a in s:
                print("sizes", a)
                all_sizes.append(a.id)
        postdata = request.POST.copy()
        postdata["psize"] = all_sizes
        print("all sizes", postdata["psize"])
        colors = request.POST.getlist("pcolor")
        all_colors = []
        for color in colors:
            print("checking fro color", color)
            s = Color.objects.filter(color=color)
            for a in s:
                print("colors", a)
                all_colors.append(a.id)
        postdata = request.POST.copy()
        postdata["pcolor"] = all_colors

        form = ProductForm(postdata, request.FILES) 
        if form.is_valid():  
            try:
                print("saving form")  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ProductForm()  
    return render(request,'add_product.html',{'form':form})

def destroy(request, id):  
    product = Product.objects.get(id=id)  
    product.delete()  
    return redirect("/show")

def edit(request, id):  
    product = Product.objects.get(id=id)  
    return render(request,'edit.html', {'product':product})

def update(request, id):  
    product = Product.objects.get(id=id)  
    form = ProductForm(request.POST, instance = product)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'product': product})

def raw_sql(request):
    name = ""
    for p in Product.objects.raw('SELECT * FROM products'):
        name = name + " " + p.pname
    return JsonResponse({'result':name})

class ProductViewset(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = serializers.ProductSerializer

    @action(
        detail=True,
        methods=['PUT'],
        serializer_class=serializers.ProductImageSerializer,
        parser_classes=[parsers.MultiPartParser],
    )
    def pic(self, request, pk):
        obj = self.get_object()
        serializer = self.serializer_class(obj, data=request.data,
                                           partial=True)
        if serializer.is_valid():
            serializer.save()
            return response.Response(serializer.data)
        return response.Response(serializer.errors,
                                 status.HTTP_400_BAD_REQUEST)

store/product/templates/add_product.html
{% extends 'layout.html' %}
{% block title %}
Add New Product
{% endblock %}

{% block content %}   
<form method="POST" class="post-form" action="/product/add_product/"
enctype="multipart/form-data">    
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label for="pid" class="col-sm-2 col-form-label">Product Id:</label>  
    <div class="col-sm-4">     
      {{ form.pid }}  
    </div>  
  </div> 

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>  
    <div class="col-sm-4">  
      {{ form.pname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Price:</label>  
    <div class="col-sm-4">  
      {{ form.pprice }}  
    </div>   
  </div>

  <div class="form-group row">  
    <label for="prating" class="col-sm-2 col-form-label">Product Rating:</label>  
    <div class="col-sm-4">  
      {{ form.prating }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Short Description:</label>  
    <div class="col-sm-4">  
      {{ form.pshort_description }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Long Description:</label>  
    <div class="col-sm-4">  
      {{ form.plong_description }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Manufacturer:</label>  
    <div class="col-sm-4">  
      {{ form.pmanufacturer }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Image:</label>  
    <div class="col-sm-4">  
      {{ form.pimage }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Color:</label>  
    <div class="col-sm-4">  
      {{ form.pcolor }}  
    </div>   
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Size:</label>  
    <div class="col-sm-4">  
      {{ form.psize }}  
    </div>   
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock %}

store/product/templates/edit.html
{% extends 'layout.html' %}
{% block title %}
Edit Product
{% endblock %}

{% block content %}   
<form method="POST" class="post-form" action="/product/update/{{product.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pid" id="id_pid" required maxlength="20" value="{{ product.pid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pname" id="id_pname" required maxlength="100" value="{{ product.pname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Price:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pprice" id="id_pprice" required maxlength="254" value="{{ product.pprice }}" />  
    </div>
    </div>    
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% block content %} 

store/product/templates/show.html
{% extends 'layout.html' %}
{% block title %}
Your Products
{% endblock %}

{% block content %}  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Product ID</th>  
        <th>Product Name</th>  
        <th>Product Price</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for product in products %}  
    <tr>  
        <td>{{ product.pid }}</td>  
        <td>{{ product.pname }}</td>  
        <td>{{ product.pprice }}</td>  
        <td>  
            <a href="/product/edit/{{ product.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/product/delete/{{ product.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="{% url 'add_product' %}" class="btn btn-primary">Add New Product</a></center>  
&nbsp;&nbsp;
{% endblock %} 